
services:
  db:
    image: mysql:9.1.0
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      DB_URL: ${DB_URL}
    #command: --skip-grant-tables
    volumes:
      - mysql-db:/var/lib/mysql
    healthcheck:
      #test: ["CMD-SHELL", "mysql --user=moses --password=Flask123! --execute 'SHOW DATABASES;' || exit 1"]
      test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\" || exit 1"
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 20s
  redis:
    image: redis/redis-stack:6.2.6-v17
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    expose:
      - 6379
      - 8001
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s 
      timeout: 20s 
      retries: 3 
      start_period: 20s
    command: [ "redis-server", "--requirepass", "$REDIS_PASSWORD"]
    volumes:
      - redis-db:/data
  api:
    build: .
    environment:
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      MAILCHIMP_TRANSACTIONAL_API_KEY: ${MAILCHIMP_TRANSACTIONAL_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PAYSTACK_SECRET_KEY: ${PAYSTACK_SECRET_KEY}
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./migrations:/src/migrations 
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /src/app
          
        - action: rebuild
          path: requirements.txt
          target: /src/requirements.txt
  front-end:
    build:
      context: ./SCHOLARFIT
      dockerfile: Dockerfile
    
    ports:
      - 3000:80
    depends_on:
      - api
    develop:
      watch:
        - action: sync+restart
          path: ./SCHOLARFIT
          target: /usr/share/nginx/html

volumes:
        mysql-db:
        redis-db:
